apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service-app
spec:
  selector:
    matchLabels:
      app: doctor-service-app
  template:
    metadata:
      labels:
        app: doctor-service-app
    spec:
      containers:
        - name: doctor-service-app
          image: IMAGE_URL/doctorservice
          resources:
            requests:
              cpu: 100m
              memory: 128Mi

          ports:
            - containerPort: 8084
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-cm
                  key: hostname


---
apiVersion: v1
kind: Service
metadata:
  name: doctor-service-svc
spec:
  type: LoadBalancer
  selector:
    app: doctor-service-app
  ports:
    - port: 80
      targetPort: 8084
